25/11/2020 10:04:08 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -help
25/11/2020 10:04:08 PM, INFO -> Help Message
25/11/2020 10:07:07 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:07:07 PM, INFO -> Display Random Quote
25/11/2020 10:07:30 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:07:30 PM, INFO -> Display Random Quote
25/11/2020 10:07:47 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:07:47 PM, INFO -> Display Random Quote
25/11/2020 10:08:11 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:08:11 PM, INFO -> Display Random Quote
25/11/2020 10:10:53 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -help
25/11/2020 10:10:53 PM, INFO -> Help Message
25/11/2020 10:13:44 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -help
25/11/2020 10:13:44 PM, INFO -> Help Message
25/11/2020 10:14:29 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -help
25/11/2020 10:14:29 PM, INFO -> Help Message
25/11/2020 10:15:13 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo "Pra ser" "Se é pra ser, siga"
25/11/2020 10:15:23 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -add "Pra ser" "Se é pra ser, siga"
25/11/2020 10:15:23 PM, INFO -> Add Quote
25/11/2020 10:15:30 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:15:30 PM, INFO -> Display Random Quote
25/11/2020 10:16:48 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo help
25/11/2020 10:16:56 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo -help
25/11/2020 10:16:56 PM, INFO -> Help Message
25/11/2020 10:17:05 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo -helperino
25/11/2020 10:17:05 PM, INFO -> Help Message
25/11/2020 10:17:21 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo add"cenas""cenas"
25/11/2020 10:17:31 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo -helpmenot
25/11/2020 10:17:31 PM, INFO -> Help Message
25/11/2020 10:18:22 PM, ERROR -> Attempting a reconnect in 0.33s
Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/client.py", line 548, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 910, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
25/11/2020 10:18:32 PM, ERROR -> Attempting a reconnect in 1.04s
Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/client.py", line 548, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 910, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
25/11/2020 10:18:43 PM, ERROR -> Attempting a reconnect in 5.37s
Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/client.py", line 548, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 910, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
25/11/2020 10:18:58 PM, ERROR -> Attempting a reconnect in 9.87s
Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/client.py", line 548, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 910, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/msilva/.local/lib/python3.6/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/msilva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
25/11/2020 10:19:54 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -helpne
25/11/2020 10:20:33 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo sdsa
25/11/2020 10:23:23 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -add "Pra ser" "Se é pra ser, que seja"
25/11/2020 10:23:23 PM, INFO -> Add Quote
25/11/2020 10:23:54 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -add "Pra ser" "Se é pra ser, que seja"
25/11/2020 10:23:54 PM, INFO -> Add Quote
25/11/2020 10:24:02 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:24:02 PM, INFO -> Display Random Quote
25/11/2020 10:24:10 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:24:10 PM, INFO -> Display Random Quote
25/11/2020 10:24:11 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:24:11 PM, INFO -> Display Random Quote
25/11/2020 10:24:13 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:24:13 PM, INFO -> Display Random Quote
25/11/2020 10:26:08 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -add "Pra ser" "Se é pra ser, siga"
25/11/2020 10:26:08 PM, INFO -> Add Quote
25/11/2020 10:26:12 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:26:12 PM, INFO -> Display Random Quote
25/11/2020 10:27:03 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo help
25/11/2020 10:27:20 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo -help
25/11/2020 10:27:20 PM, INFO -> Help Message
25/11/2020 10:28:51 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo help
25/11/2020 10:29:09 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo -add "Hello "world"" "A simple "hello world""
25/11/2020 10:29:17 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo help
25/11/2020 10:29:43 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo help
25/11/2020 10:29:43 PM, INFO -> Help Message
25/11/2020 10:29:50 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo add "Hello "world"" "A simple "hello world""
25/11/2020 10:29:50 PM, INFO -> Add Quote
25/11/2020 10:29:50 PM, ERROR -> Error, wrong usage
25/11/2020 10:30:36 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo add "Hello world" "A simple hello world
25/11/2020 10:30:36 PM, INFO -> Add Quote
25/11/2020 10:30:36 PM, ERROR -> Error, wrong usage
25/11/2020 10:30:41 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo add "Hello world" "A simple hello world"
25/11/2020 10:30:41 PM, INFO -> Add Quote
25/11/2020 10:30:41 PM, ERROR -> Error, wrong usage
25/11/2020 10:30:49 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:30:49 PM, INFO -> Display Random Quote
25/11/2020 10:30:56 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:30:56 PM, INFO -> Display Random Quote
25/11/2020 10:31:00 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:00 PM, INFO -> Display Random Quote
25/11/2020 10:31:04 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:04 PM, INFO -> Display Random Quote
25/11/2020 10:31:06 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:06 PM, INFO -> Display Random Quote
25/11/2020 10:31:07 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:07 PM, INFO -> Display Random Quote
25/11/2020 10:31:08 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:08 PM, INFO -> Display Random Quote
25/11/2020 10:31:10 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:10 PM, INFO -> Display Random Quote
25/11/2020 10:31:11 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:11 PM, INFO -> Display Random Quote
25/11/2020 10:31:12 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:12 PM, INFO -> Display Random Quote
25/11/2020 10:31:14 PM, INFO -> Taliscas & Company, autismo-geral, Tchibarazz: !quo random
25/11/2020 10:31:14 PM, INFO -> Display Random Quote
25/11/2020 10:31:14 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo add "Hello world"
25/11/2020 10:31:14 PM, INFO -> Add Quote
25/11/2020 10:31:14 PM, ERROR -> Error, wrong usage
25/11/2020 10:31:32 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo add "Hello world" "A simple hello world"
25/11/2020 10:31:32 PM, INFO -> Add Quote
25/11/2020 10:31:47 PM, INFO -> Taliscas & Company, autismo-geral, Fotomik: !quo add "Hello "world"" "A simple "hello world""
25/11/2020 10:31:47 PM, INFO -> Add Quote
25/11/2020 10:31:47 PM, ERROR -> Error, wrong usage
25/11/2020 10:32:08 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo -random
25/11/2020 10:32:13 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo random
25/11/2020 10:32:13 PM, INFO -> Display Random Quote
25/11/2020 10:36:15 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo help
25/11/2020 10:36:15 PM, INFO -> Help Message
25/11/2020 10:36:24 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo a
25/11/2020 10:36:34 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo add a
25/11/2020 10:36:34 PM, INFO -> Add Quote
25/11/2020 10:36:34 PM, ERROR -> Error, wrong usage
25/11/2020 10:37:19 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo add a
25/11/2020 10:37:19 PM, INFO -> Add Quote
25/11/2020 10:37:19 PM, ERROR -> Error, wrong usage
25/11/2020 10:39:42 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo add
25/11/2020 10:39:50 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo help
25/11/2020 10:39:50 PM, INFO -> Help Message
25/11/2020 10:39:53 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo add asa
25/11/2020 10:39:53 PM, INFO -> Add Quote
25/11/2020 10:39:53 PM, ERROR -> Error, wrong usage
25/11/2020 10:40:00 PM, INFO -> Taliscas & Company, autismo-geral, you: !quo random
25/11/2020 10:40:00 PM, INFO -> Display Random Quote
